name: Mobile Automation Test
on:
  push:
    branches:
      - main

  schedule:
    - cron: '0 11,15,19 * * *' # 8h, 12h e 16h
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.7'

      - name: Instalar dependencies
        run: pip install -r requirements.txt

#      - name: Atualziar pip
#        run: pip install --upgrade pip 

      - name: Executar testes
        run: |
          robot -d ./logs -i suc tests/login.robot

#      - name: Upload logs and reports
#        uses: actions/upload-artifact@v3
#        if: always()
#        with:
#          name: logs-and-reports
#          path: ./logs
#          retention-days: 30

#      - name: Notificar Discord com resultado
#        if: always()
#        run: |
#          STATUS="SUCESSO"
#          if [ "${{ job.status }}" != "success" ]; then STATUS="FALHA"; fi
#          curl -X POST -H "Content-Type: application/json" \
#          -d "{\"content\": \"${STATUS}  E ai time de QA, Segue o relatório da execução da MUPAY para verificar mais detalhes: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\"}" \
#          ${{ secrets.DISCORD_WEBHOOK_URL }}
